version: "3.4"
services:

  db-react:
    image: postgres:12.2
    container_name: db-react
    ports:
      - 5444:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
       - app-network 

  backend-react:
    build: 
      context: .
      dockerfile: ./compose/Dockerfile.backend
    container_name: backend-react
    image: backend-react
    depends_on:
      - db-react     
    ports:
      - 3080:3080
    volumes:
      - ./app/backend:/var/www/app/backend
      - shared_volume:/var/www/static
    command: python manage.py runserver 0.0.0.0:3080
    tty: true
    networks:
       - app-network

  frontend-react:
    build: 
      context: .
      dockerfile: ./compose/Dockerfile.frontend
    container_name: frontend-react
    image: frontend-react
    ports:
      - 3000:3000
    volumes:
      - ./app/frontend/:/var/www/app/frontend
      - shared_volume:/var/www/static
    command: npm run dev
    tty: true
    networks:
       - app-network

volumes:
  shared_volume:
  pgdata:

networks:
  app-network:
