version: "3.4"
services:

  db-xrays:
    image: postgres:12.2
    container_name: db-xrays
    ports:
      - 5444:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
       - app-network 

  backend-xrays:
    build: 
      context: .
      dockerfile: ./compose/Dockerfile.backend
    container_name: backend-xrays
    image: backend-xrays
    depends_on:
      - db-xrays      
    ports:
      - 3080:3080
    volumes:
      - ./app/backend:/var/www/app/backend
      - shared_volume:/var/www/static
    command: python manage.py runserver 0.0.0.0:3080
    tty: true
    networks:
       - app-network

  frontend-xrays:
    build: 
      context: .
      dockerfile: ./compose/Dockerfile.frontend
    container_name: frontend-xrays
    image: frontend-xrays
    ports:
      - 3000:3000
    volumes:
      - ./app/frontend/:/var/www/app/frontend
      - shared_volume:/var/www/static
    command: npm run dev
    tty: true
    networks:
       - app-network

volumes:
  shared_volume:

networks:
  app-network:
